# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20171011_1742'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdevice',
            name='category',
        ),
        migrations.AddField(
            model_name='projectdevice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Category', verbose_name='Категория оборудования'),
        ),
    ]
