# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.CharField(max_length=256, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
