# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171011_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
    ]
