# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171010_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.CharField(max_length=256, null=True, verbose_name='ID cсылки на видео'),
        ),
    ]
