# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171012_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Выводить на главной'),
        ),
    ]
