# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 19:46
from __future__ import unicode_literals

import app.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover',
            field=models.ImageField(blank=True, upload_to=app.services.models.upload_to, verbose_name='Выбрать фотографию обложки'),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='cover',
            field=models.ImageField(blank=True, upload_to=app.services.models.upload_to, verbose_name='Выбрать фотографию подпункта'),
        ),
    ]
