# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottomslide',
            options={'ordering': ['sort_index'], 'verbose_name': 'Нижний слайд', 'verbose_name_plural': 'Нижние слайды'},
        ),
        migrations.AlterModelOptions(
            name='topslide',
            options={'ordering': ['sort_index'], 'verbose_name': 'Верхний слайд', 'verbose_name_plural': 'Верхние слайды'},
        ),
        migrations.AddField(
            model_name='bottomslide',
            name='sort_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='topslide',
            name='sort_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
    ]
