# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:02
from __future__ import unicode_literals

import app.services.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории')),
                ('cover', models.ImageField(blank=True, upload_to=app.services.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('short_desc', models.TextField(null=True, verbose_name='Короткое описание для главной')),
            ],
            options={
                'verbose_name': 'Категория',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название услуги')),
                ('cover', models.ImageField(blank=True, upload_to=app.services.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('is_main', models.BooleanField(default=False, verbose_name='Выводить на главной')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('tag', models.BooleanField(default=False, verbose_name='Новинка')),
                ('producer_link', models.URLField(null=True, verbose_name='Ссылка на описание производителя')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание проекта')),
                ('you_tube_link', models.URLField(null=True, verbose_name='Ссылка на демо видео')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Производитель')),
                ('country', models.CharField(max_length=128, verbose_name='Страна')),
                ('cover', models.ImageField(blank=True, upload_to=app.services.models.upload_to, verbose_name='Логотип производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название подкатегории')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_subcategories', to='devices.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_producers', to='devices.Producer', verbose_name='Производитель'),
        ),
    ]
