# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20171008_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_desc',
            field=models.TextField(null=True, verbose_name='Короткое описание для главной'),
        ),
    ]
