# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:13
from __future__ import unicode_literals

import app.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20171011_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_index'], 'verbose_name': 'Категория оборудования', 'verbose_name_plural': 'Категории оборудования'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'Производитель оборудования', 'verbose_name_plural': 'Производители оборудования'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sort_index'], 'verbose_name': 'Подкатегория оборудования', 'verbose_name_plural': 'Подкатегории оборудования'},
        ),
        migrations.AddField(
            model_name='category',
            name='ikon',
            field=models.ImageField(blank=True, upload_to=app.services.models.upload_to, verbose_name='Выбрать иконку для главной'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название оборудования'),
        ),
    ]
