# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20171011_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ikon',
        ),
        migrations.AlterField(
            model_name='devices',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_producers', to='devices.Producer', verbose_name='Производитель'),
        ),
    ]
