# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20171010_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='you_tube_link',
            field=models.URLField(null=True, verbose_name='Ссылка на демо видео'),
        ),
    ]
