# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20171011_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание оборудования'),
        ),
    ]
