# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20171012_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='is_main',
        ),
    ]
