# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_devices_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание оборудования'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='producer_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на описание производителя'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='you_tube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на демо видео'),
        ),
    ]
